In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
import torch
import torch.nn as nn

vocab_size = 1000
d_model = 512      # 嵌入维度，也是 Transformer 的模型维度
nhead = 8          # 多头注意力头数（必须整除 d_model）
seq_len = 10
batch_size = 32

In [3]:
# 1. Embedding 层：将 token IDs 转为 dense vectors
embedding = nn.Embedding(vocab_size, d_model)  # 输出: (batch, seq, d_model)

In [4]:
# 2. 输入 token IDs（假设已 padding）
input_ids = torch.randint(0, vocab_size, (batch_size, seq_len))  # (32, 10)

In [5]:
x = embedding(input_ids)  # shape: (32, 10, 512)

In [6]:
encoder_layer = nn.TransformerEncoderLayer(
    d_model=d_model,   # ← 必须等于 embedding 的 dim
    nhead=nhead,       # ← 决定内部如何拆分注意力头
    batch_first=True
)

In [7]:
output = encoder_layer(x)  # shape: (32, 10, 512) —— 维度不变！

In [8]:
embedding.weight.shape

torch.Size([1000, 512])

In [9]:
x.shape

torch.Size([32, 10, 512])

In [10]:
print(x)

tensor([[[ 0.1647, -0.3085,  1.0952,  ..., -0.4182,  0.6224,  0.9236],
         [-0.5490, -0.3168, -0.8426,  ...,  0.2688, -0.2423, -0.3333],
         [ 0.6672,  0.3188,  0.3514,  ...,  1.6089,  1.0639,  0.3676],
         ...,
         [ 0.4677, -1.6339, -0.2655,  ..., -0.4746, -0.6595, -0.5544],
         [-0.4466,  0.0138, -3.4896,  ...,  1.0505, -0.8704, -1.1786],
         [-0.0698, -1.0421,  1.4685,  ...,  1.1292,  0.5555,  0.2181]],

        [[ 0.3979,  2.1153,  0.8561,  ..., -1.0947,  0.7962,  0.8197],
         [ 0.6449, -0.0062,  0.6563,  ..., -0.8089,  1.1921,  0.0762],
         [-0.1759,  0.7744, -0.0060,  ..., -0.5796,  0.1568,  0.3155],
         ...,
         [-1.2795,  0.8664,  0.0287,  ..., -1.6289,  0.7865,  0.1139],
         [ 0.4173,  1.0536, -1.9627,  ..., -1.2910, -1.5000, -1.2034],
         [ 1.1759, -0.3368, -0.6095,  ..., -0.8134, -1.5944,  1.0804]],

        [[-0.1705,  0.3860,  1.5224,  ...,  0.5696, -0.3932, -0.5377],
         [-1.3352,  0.4999, -0.4728,  ..., -1

In [11]:
pos_encoding = nn.Parameter(torch.zeros(1, seq_len, d_model))

In [12]:
print(pos_encoding)

Parameter containing:
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], requires_grad=True)


In [13]:
print(pos_encoding.shape)

torch.Size([1, 10, 512])


In [14]:
print(x.shape)

torch.Size([32, 10, 512])


In [15]:
# 训练前
print("Before training:", model.pos_encoding[0, 0, :3])  # 前3维
# 输出: tensor([0., 0., 0.], grad_fn=<SliceBackward0>)

# 训练一个 batch
optimizer.zero_grad()
logits = model(train_src[:2])
loss = criterion(logits.view(-1, vocab_size), train_tgt[:2].view(-1))
loss.backward()
optimizer.step()

# 训练后
print("After training:", model.pos_encoding[0, 0, :3])
# 输出: tensor([-0.0021, 0.0045, -0.0012], ...) ← 不再是 0！

NameError: name 'model' is not defined

In [17]:
import torch
import torch.nn as nn

# 创建线性层：输入3维 → 输出2维
linear = nn.Linear(in_features=3, out_features=2, bias=True)

# 手动设置参数（仅用于演示）
with torch.no_grad():
    linear.weight = nn.Parameter(torch.tensor([[1.0, 2.0, 3.0],
                                              [4.0, 5.0, 6.0]]))  # shape [2, 3]
    linear.bias = nn.Parameter(torch.tensor([0.1, 0.2]))            # shape [2]

# 输入: [2, 3] （batch=2, feature=3）
x = torch.tensor([[1.0, 1.0, 1.0],
                  [2.0, 0.0, 1.0]])

# 前向计算
y = linear(x)
print(y)

tensor([[ 6.1000, 15.2000],
        [ 5.1000, 14.2000]], grad_fn=<AddmmBackward0>)


In [18]:
linear = nn.Linear(4, 2)
x = torch.randn(4)          # shape: [4]
y = linear(x)               # shape: [2]

In [19]:
print(x)
print(y)

tensor([-0.0554, -0.0902,  0.9343, -1.6278])
tensor([-1.0755, -0.3322], grad_fn=<ViewBackward0>)
